# Generated by Django 5.2.8 on 2025-12-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_categorymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
