# Generated by Django 5.2.8 on 2025-12-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
