# Generated by Django 5.2.8 on 2025-12-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_productitem_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='special_instraction',
            field=models.TextField(blank=True, default='none', max_length=1000, null=True),
        ),
    ]
