# Generated by Django 5.2.8 on 2025-12-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_profile_chat_id_profile_is_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
