"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from environ import Env

import dj_database_url

env = Env()

Env.read_env()
ENVIRONMENT = env("ENVIRONMENT", default="production")
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

REDIS_URL = env("REDIS_URL")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

if ENVIRONMENT == "development":
    DEBUG = True
else:
    DEBUG = False

ALLOWED_HOSTS = [
    "192.168.43.7",
    "192.168.30.186",
    'localhost',
    '127.0.0.1',
    "192.168.17.186",
    '.railway.app',
    "*"
    # Allows all Railway subdomains
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'delivery',
    'channels',
]

INSTALLED_APPS += ['storages']

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.common.CommonMiddleware',
]


if ENVIRONMENT == "development":
    CORS_ALLOW_ALL_ORIGINS = True
    CSRF_TRUSTED_ORIGINS = ["http://localhost:5173/", "http://192.168.43.7:5173"]
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        "https://liyudeliveryfrontend-production.up.railway.app",
        "https://liyudelivery.hailecw27.workers.dev",
        "https://*.railway.app",
    ]
    CSRF_TRUSTED_ORIGINS = [
        'https://*.railway.app',
        'https://liyudelivery.hailecw27.workers.dev',
    ]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True


CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

print(ENVIRONMENT)

if ENVIRONMENT == "production":
    DATABASES = {
        'default': dj_database_url.config(
            env="DATABASE_URL",
            conn_max_age=600,
            ssl_require=True,  # set False only if your DB doesn't need SSL (e.g. same private network)
        )
    }

    # --- Supabase S3-compatible storage for media files (PUBLIC bucket) ---
    AWS_ACCESS_KEY_ID = env("SUPABASE_S3_ACCESS_KEY")
    AWS_SECRET_ACCESS_KEY = env("SUPABASE_S3_SECRET_KEY")
    AWS_STORAGE_BUCKET_NAME = env("SUPABASE_BUCKET_NAME")       # e.g. "LiyuDelivery"
    AWS_S3_ENDPOINT_URL = env("SUPABASE_S3_ENDPOINT")           # e.g. https://xxxx.supabase.co/storage/v1/s3
    AWS_S3_REGION_NAME = env("SUPABASE_S3_REGION", default="us-east-1")

    AWS_S3_ADDRESSING_STYLE = 'path'      # Supabase needs path-style, not virtual-hosted
    AWS_S3_SIGNATURE_VERSION = 's3v4'     # required for non-AWS endpoints
    AWS_S3_FILE_OVERWRITE = False

    # Derive the project ref from AWS_S3_ENDPOINT_URL
    # (e.g. https://abcxyz.supabase.co/storage/v1/s3 -> "abcxyz")
    _SUPABASE_HOST = AWS_S3_ENDPOINT_URL.split('//')[1].split('.supabase.co')[0]

    # Bucket is public: build file URLs from Supabase's public object path
    # instead of the S3 API endpoint (django-storages ignores MEDIA_URL
    # for field .url values, so this is what actually controls it).
    AWS_S3_CUSTOM_DOMAIN = f"{_SUPABASE_HOST}.supabase.co/storage/v1/object/public/{AWS_STORAGE_BUCKET_NAME}"
    AWS_QUERYSTRING_AUTH = False  # no signed query params needed on a public bucket

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    MEDIA_ROOT = BASE_DIR / 'media'
    MEDIA_URL = '/media/'
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }


if ENVIRONMENT == "production":
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
